### ISSUE TITLE
Live validation mode

### ISSUE THREAD

**Issue by aristidesfl** [xrado/vue-validator#4]
Most inputs should validate on blur like they do now, but in some special cases it would be useful to have live validation as the user is typing. 
Would it be possible to have some kind of option to enable this functionality in specific inputs?

Cheers

**Comment by aristidesfl** [comment]
I've came up with a workaround in the meanwhile: http://jsbin.com/tepuluxoye/1/edit?html,output
Had to modify vue-validator though: http://jsbin.com/tepuluxoye/1/edit?html,output

Is there a better way to do this?

**Comment by shredmaster** [comment]
http://vuejs.org/guide/forms.html
maybe a better solution would be set watch on model value and let the lazy attribute to handle how you want to update the value and then trigger the validation event accordingly.

**Comment by aristidesfl** [comment]
You mean, instead of hooking on onBlur? That sounds like an awesome idea.
The only problem would be if you need live value updating and lazy validation, which is how it works currently.

**Comment by xrado** [comment]
I'm thinking of adding another option validateOn: 'blur' (by default) or on 'change' and also allowing setting multiple validtion options. For instance validateOn: ['start','change','blur'].

What do you think?

**Comment by shredmaster** [comment]
By default, v-model syncs the input with the data after each input event. You can add a lazy attribute to change the behavior to sync after change events:

if we change v-valid to bind after v-model and watch for value change, that should take care the "validate as you type" and "validate onblur" use case. 

I am making assumption that this change couple behaviors which i think is more desired:
1) avoid validate on page load, or reload. I think it's annoy to show invalid indicator before user actually typing anything in the field, ie. required rule.

2) correctly set the modified attribute. Because order directive is binded, the startValue is always undefined and different from model when v-model update the value. Hence, the modified attribute is always set to true.

As for "start" event, if default value is coming from server side, the value should be sanitized already. I can't think of use case where I need "start" event right now. If default value is populated by auto complete, it should be same as "validate as you type".

with that being said, I spent couple hours this afternoon playing with the idea. I didn't go very far because this.el.getAttribute(Vue.config.prefix+'model') is always undefined when v-valid directive is initialized. I have no idea where and when the v-model attribute gets removed.

btw, this is by far the best validation framework I've came across. thank you very much for your great work.

**Comment by xrado** [comment]
@shredmaster you are right, I've just pushed simplified validation logic. Validation on start is removed, but you can still invoke it manually by emitting validate event. I've also fixed modified status by attaching watcher after model initialization. Validation can be now controlled with lazy option. I like it better now

**Comment by shredmaster** [comment]
Thanks for the quick fix. Can you explain why touched field was removed and introduced?

**Comment by xrado** [comment]
Touched was intended to validate only inputs that were touched (got focus) by user

**Comment by aristidesfl** [comment]
But now there is no need for touched?

**Comment by aristidesfl** [comment]
How to achieve live validation which only starts after the first blur though?

**Comment by xrado** [comment]
ha, I've totally forgot about this scenario. Looks like I'll have to rethink all over again.

**Comment by aristidesfl** [comment]
Any ideas on this?

**Comment by xrado** [comment]
You'll probably have to figure out yourself. Currently I don't have time to play with this.

**Comment by aristidesfl** [comment]
What if:
When the blur event is triggered we add a 'blurred' class to the element.
It would be easy to target with css `.invalid.blurred {}` and could be combined with the lazy mechanism. And available for other things via `vm.validator.[property].blurred`.
